/*Trigger*/
DROP TRIGGER IF EXISTS createMatricule;
DELIMITER //
CREATE TRIGGER createMatricule BEFORE INSERT
ON employe
FOR EACH ROW
BEGIN
SET NEW.matricule= CONCAT(UPPER(SUBSTR(NEW.nom,1,2)),'-',YEAR(NEW.dateNaissance),'-',FLOOR(RAND()*(99-10+1)+10));
END //
DELIMITER ;

DROP TRIGGER IF EXISTS createIdClient;
DELIMITER //
CREATE TRIGGER createIdClient BEFORE INSERT
ON client
FOR EACH ROW
BEGIN
SET NEW.id= FLOOR(RAND()*(999-100+1)+100);
END //
DELIMITER ;

DROP TRIGGER IF EXISTS createNoProjet;
DELIMITER //
CREATE TRIGGER createNoProjet BEFORE INSERT
ON projet
FOR EACH ROW
BEGIN
SET NEW.noProjet= CONCAT(NEW.idClient,'-',FLOOR(RAND()*(99-01+1)+01),'-',YEAR(NEW.dateDebut));
END //
DELIMITER ;

DROP TRIGGER IF EXISTS SalaireMIN;
DELIMITER //
CREATE TRIGGER SalaireMIN BEFORE INSERT
ON employe
FOR EACH ROW
BEGIN
IF NEW.tauxHoraire<15 THEN
SET NEW.tauxHoraire= 15;
END IF;
END //
DELIMITER ;

DROP TRIGGER IF EXISTS BudgetMIN;
DELIMITER //
CREATE TRIGGER BudgetMIN BEFORE INSERT
ON projet
FOR EACH ROW
BEGIN
IF NEW.budget<0 THEN
SET NEW.budget= 1;
END IF;
END //
DELIMITER ;